#!/bin/bash

echo "======================================"
echo "Claude Code Authentication Helper"
echo "======================================"
echo ""
echo "This script will help you authenticate Claude Code on Fly.io"
echo ""
echo "Step 1: SSH into your Fly.io machine"
echo "--------------------------------------"
echo "Run this command:"
echo "  fly ssh console --app uncle-frank-claude"
echo ""
echo "Step 2: Once connected, attach to Claude's tmux session"
echo "---------------------------------------------------------"
echo "Run this command inside SSH:"
echo "  tmux attach -t claude"
echo ""
echo "Step 3: Authenticate Claude"
echo "----------------------------"
echo "You'll see a login screen. Choose:"
echo "  - Press '2' for Anthropic Console (API key)"
echo "  - Press '1' for Claude subscription"
echo ""
echo "If using API key (option 2):"
echo "  - Enter your API key when prompted"
echo "  - The key starts with 'sk-ant-api...'"
echo ""
echo "Step 4: Detach from tmux (keep Claude running)"
echo "------------------------------------------------"
echo "Press: Ctrl+B then D"
echo ""
echo "Step 5: Exit SSH"
echo "-----------------"
echo "Type: exit"
echo ""
echo "======================================"
echo "Alternative: Set API key as environment variable"
echo "======================================"
echo ""
echo "You can also set your API key as a Fly secret:"
echo "  fly secrets set ANTHROPIC_API_KEY='your-api-key-here' --app uncle-frank-claude"
echo ""
echo "Then restart the app:"
echo "  fly apps restart uncle-frank-claude"
echo ""