#!/bin/bash

echo "🚀 Quick Deploy to Vercel (Easiest Option)"
echo "=========================================="
echo ""
echo "Run this single command:"
echo ""
echo "  npx vercel --prod"
echo ""
echo "Or deploy via web:"
echo "  1. Go to https://vercel.com/new"
echo "  2. Import this repository"
echo "  3. Deploy with zero config!"
echo ""
echo "Your app will be live in seconds at:"
echo "https://[your-app].vercel.app"
