version: '3.8'

services:
  claudecodeui:
    build: .
    container_name: claudecodeui
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - PORT=3001
    volumes:
      # Mount Claude configuration from host (optional)
      # Uncomment if you want to use host's Claude configuration
      # - ~/.claude:/home/nodejs/.claude
      
      # Mount for persistent database
      - ./data:/app/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:3001/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s